baseURL = 'https://blog.appr.me/'
languageCode = 'en-us'
title = '~/blog'
theme = "gokarna"
enableRobotsTXT = true
enableEmoji = true

[menu]
  [[menu.main]]
    identifier = "posts"
    url = "/posts/"
    pre = ""
    post = ""
    name = "Posts"
    weight = 1

  [[menu.main]]
    identifier = "linkedin"
    url = "https://www.linkedin.com/in/apprme"
    weight = 2
    pre = "<span data-feather='linkedin'></span>"

  [[menu.main]]
    identifier = "facebook"
    url = "https://www.facebook.com/pavel.kakolin"
    weight = 3
    pre = "<span data-feather='facebook'></span>"

  [[menu.main]]
    identifier = "instagram"
    url = "https://instagram.com/appr"
    weight = 4
    pre = "<span data-feather='instagram'></span>"

  [[menu.main]]
    identifier = "telegram"
    url = "https://t.me/appr_me"
    weight = 4
    pre = "<span data-feather='send'></span>"

  [[menu.main]]
    identifier = "strava"
    url = "https://strava.com/athletes/7562844"
    weight = 4
    pre = "<img style='width: 20px; fill: currentColor; stroke: none;' class='svg-inject' src='/images/strava.svg' />"

[params]
  avatarURL = "/images/userpic.jpg"
  avatarSize = "size-xs"
  description = ""
  metaKeywords = []
  showPostsOnHomePage = "recent"
  footer = "appr"